// estoque-angular/src/app/features/estoque/estoque.component.ts
import { Component, OnInit, OnDestroy, ViewChild, ElementRef, inject, ChangeDetectorRef, NgZone } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ProdutoService } from '../../services/produto.service';
import { Produto, ProdutoRequest } from '../../models/produto.model';

import { SearchBarComponent } from '../../shared/components/search-bar/search-bar.component';
import { ActionButtonComponent } from '../../shared/components/action-button/action-button.component';
import { TabelaProdutosComponent } from './components/tabela-produtos/tabela-produtos.component';
import { ModalCadastrarProdutoComponent } from './components/modal-cadastrar-produto/modal-cadastrar-produto.component';

@Component({
  selector: 'app-estoque',
  standalone: true,
  imports: [
    CommonModule,
    SearchBarComponent,
    ActionButtonComponent,
    TabelaProdutosComponent,
    ModalCadastrarProdutoComponent
  ],
  templateUrl: './estoque.component.html'
})
export class EstoqueComponent implements OnInit, OnDestroy {
  private produtoService = inject(ProdutoService);
  
  // INJETANDO AS FERRAMENTAS DE ATUALIZAÇÃO DE TELA DO ANGULAR
  private cdr = inject(ChangeDetectorRef);
  private ngZone = inject(NgZone);

  produtos: Produto[] = [];
  modalCadastroAberto = false;
  loading = true;
  loadingMore = false;
  busca = '';
  paginaAtual = 0;
  hasMore = true;

  private observer: IntersectionObserver | null = null;

  @ViewChild('observerTarget') set target(element: ElementRef) {
    if (element) {
      this.configurarObserver(element.nativeElement);
    }
  }

  get produtosFiltrados(): Produto[] {
    if (!this.busca) return this.produtos;
    return this.produtos.filter(p => 
      p.nome.toLowerCase().includes(this.busca.toLowerCase())
    );
  }

  ngOnInit() {
    this.carregarProdutos(0, true);
  }

  ngOnDestroy() {
    if (this.observer) {
      this.observer.disconnect();
    }
  }

  private configurarObserver(elemento: HTMLElement) {
    if (this.observer) {
      this.observer.disconnect();
    }

    // Colocamos o Observer para rodar fora do Angular para não travar a tela...
    this.ngZone.runOutsideAngular(() => {
      this.observer = new IntersectionObserver((entries) => {
        if (entries[0].isIntersecting && this.hasMore && !this.loadingMore && !this.loading) {
          
          // ...Mas quando precisamos carregar mais itens, chamamos de volta para dentro do Angular!
          this.ngZone.run(() => {
            this.carregarProdutos(this.paginaAtual + 1, false);
          });
          
        }
      }, { 
        rootMargin: '200px',
        threshold: 0.1 
      });

      this.observer.observe(elemento);
    });
  }

  carregarProdutos(page: number, reset: boolean = false) {
    if (reset) {
      this.loading = true;
    } else {
      this.loadingMore = true;
    }
    this.cdr.detectChanges(); // Força a tela a mostrar o spinner

    this.produtoService.listarProdutos(page, 10).subscribe({
      next: (data) => {
        if (reset) {
          this.produtos = data.content;
        } else {
          this.produtos = [...this.produtos, ...data.content];
        }
        this.hasMore = !data.last;
        this.paginaAtual = page;
        this.cdr.detectChanges(); // Força a tela a desenhar os novos produtos
      },
      error: (error) => {
        console.error("Erro ao carregar produtos:", error);
        this.cdr.detectChanges();
      },
      complete: () => {
        this.loading = false;
        this.loadingMore = false;
        this.cdr.detectChanges(); // Força a tela a esconder o spinner
      }
    });
  }

  atualizarBusca(novaBusca: string) {
    this.busca = novaBusca;
  }

  abrirModalCadastro() {
    this.modalCadastroAberto = true;
  }

  fecharModalCadastro() {
    this.modalCadastroAberto = false;
  }

  handleUpdateQuantidade(evento: { id: number, delta: number }) {
    const produto = this.produtos.find(p => p.id === evento.id);
    if (!produto) return;

    const novaQuantidade = Math.max(0, produto.quantidade + evento.delta);
    const payload: ProdutoRequest = {
      nome: produto.nome,
      tipo: produto.tipo,
      unidade: produto.unidade,
      quantidade: novaQuantidade
    };

    this.produtoService.atualizarProduto(evento.id, payload).subscribe({
      next: (atualizado) => {
        this.produtos = this.produtos.map(p => p.id === evento.id ? atualizado : p);
        this.cdr.detectChanges();
      },
      error: (error) => console.error("Erro ao atualizar quantidade:", error)
    });
  }

  handleSetQuantidade(evento: { id: number, quantidade: number }) {
    const produto = this.produtos.find(p => p.id === evento.id);
    if (!produto) return;

    const novaQuantidade = Math.max(0, evento.quantidade);
    const payload: ProdutoRequest = {
      nome: produto.nome,
      tipo: produto.tipo,
      unidade: produto.unidade,
      quantidade: novaQuantidade
    };

    this.produtoService.atualizarProduto(evento.id, payload).subscribe({
      next: (atualizado) => {
        this.produtos = this.produtos.map(p => p.id === evento.id ? atualizado : p);
        this.cdr.detectChanges();
      },
      error: (error) => console.error("Erro ao definir quantidade:", error)
    });
  }

  handleCadastrarProduto(novoProduto: any) {
    const payload: ProdutoRequest = { ...novoProduto, quantidade: 0 };
    
    this.produtoService.cadastrarProduto(payload).subscribe({
      next: (criado) => {
        this.produtos = [...this.produtos, criado];
        this.fecharModalCadastro();
        this.cdr.detectChanges();
      },
      error: (error) => console.error("Erro ao cadastrar produto:", error)
    });
  }

  handleExcluirProduto(id: number) {
    this.produtoService.excluirProduto(id).subscribe({
      next: () => {
        this.produtos = this.produtos.filter(p => p.id !== id);
        this.cdr.detectChanges();
      },
      error: (error) => console.error("Erro ao excluir produto:", error)
    });
  }

  handleEditarProduto(produtoEditado: Produto) {
    const payload: ProdutoRequest = {
      nome: produtoEditado.nome,
      tipo: produtoEditado.tipo,
      unidade: produtoEditado.unidade,
      quantidade: produtoEditado.quantidade
    };

    this.produtoService.atualizarProduto(produtoEditado.id, payload).subscribe({
      next: (atualizado) => {
        this.produtos = this.produtos.map(p => p.id === atualizado.id ? atualizado : p);
        this.cdr.detectChanges();
      },
      error: (error) => console.error("Erro ao editar produto:", error)
    });
  }
}
<div class="min-h-screen bg-[#F3F3F3]">
  <header class="bg-[#2C2C32] py-4 px-6 xl:py-6 xl:px-8">
    <div class="max-w-5xl xl:max-w-6xl mx-auto flex items-center justify-between">
      
      <app-search-bar 
        [value]="busca" 
        (onChange)="atualizarBusca($event)">
      </app-search-bar>

      <div class="flex items-center gap-3 xl:gap-4">
        <app-action-button (onClick)="abrirModalCadastro()">
          Cadastrar produto
        </app-action-button>
      </div>
    </div>
  </header>

  <main class="max-w-5xl xl:max-w-6xl mx-auto py-6 px-6 xl:py-8 xl:px-8">
    
    <div *ngIf="loading" class="flex justify-center items-center py-12">
      <p class="text-gray-500">Carregando produtos...</p>
    </div>

    <ng-container *ngIf="!loading">
      
      <app-tabela-produtos
        [produtos]="produtosFiltrados"
        (onUpdateQuantidade)="handleUpdateQuantidade($event)"
        (onSetQuantidade)="handleSetQuantidade($event)"
        (onEditarProduto)="handleEditarProduto($event)"
        (onExcluirProduto)="handleExcluirProduto($event)">
      </app-tabela-produtos>
      
      <div #observerTarget class="h-4"></div>
      
      <div *ngIf="loadingMore" class="flex justify-center items-center py-6">
        <p class="text-gray-500">Carregando mais produtos...</p>
      </div>
      
      <div *ngIf="!hasMore && produtos.length > 0" class="flex justify-center items-center py-6">
        <p class="text-gray-400 text-sm">Todos os produtos foram carregados</p>
      </div>
    </ng-container>
  </main>

  <app-modal-cadastrar-produto
    [isOpen]="modalCadastroAberto"
    (onClose)="fecharModalCadastro()"
    (onCadastrar)="handleCadastrarProduto($event)">
  </app-modal-cadastrar-produto>
</div>

// estoque-frontend/app/components/Estoque.tsx
"use client";

import { useState, useEffect, useRef } from "react";
import SearchBar from "./ui/SearchBar";
import ActionButton from "./ui/ActionButton";
import TabelaProdutos, { Produto } from "./ui/TabelaProdutos";
import ModalCadastrarProduto from "./ui/ModalCadastrarProduto";
import * as api from "../services/api";

export default function Estoque() {
  const [produtos, setProdutos] = useState<Produto[]>([]);
  const [modalCadastroAberto, setModalCadastroAberto] = useState(false);
  const [loading, setLoading] = useState(true);
  const [loadingMore, setLoadingMore] = useState(false);
  const [busca, setBusca] = useState("");
  const [paginaAtual, setPaginaAtual] = useState(0);
  const [hasMore, setHasMore] = useState(true);
  const observerTarget = useRef<HTMLDivElement>(null);

  // Filtrar produtos pela busca
  const produtosFiltrados = produtos.filter((produto) =>
    produto.nome.toLowerCase().includes(busca.toLowerCase())
  );

  // Carregar produtos ao montar o componente
  useEffect(() => {
    carregarProdutos(0, true);
  }, []);

  const carregarProdutos = async (page: number, reset: boolean = false) => {
    if (reset) {
      setLoading(true);
    } else {
      setLoadingMore(true);
    }

    try {
      const data = await api.listarProdutos(page, 10);
      
      if (reset) {
        setProdutos(data.content);
      } else {
        setProdutos((prev) => [...prev, ...data.content]);
      }
      
      setHasMore(!data.last);
      setPaginaAtual(page);
    } catch (error) {
      console.error("Erro ao carregar produtos:", error);
    } finally {
      setLoading(false);
      setLoadingMore(false);
    }
  };

  // Observar o elemento sentinela para carregar mais
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting && hasMore && !loadingMore && !loading) {
          carregarProdutos(paginaAtual + 1, false);
        }
      },
      { threshold: 1.0 }
    );

    const currentTarget = observerTarget.current;
    
    if (currentTarget) {
      observer.observe(currentTarget);
    }

    return () => {
      if (currentTarget) {
        observer.unobserve(currentTarget);
      }
    };
  }, [hasMore, loadingMore, loading, paginaAtual]);

  const handleUpdateQuantidade = async (id: number, delta: number) => {
    const produto = produtos.find((p) => p.id === id);
    if (!produto) return;

    const novaQuantidade = Math.max(0, produto.quantidade + delta);
    try {
      const atualizado = await api.atualizarProduto(id, {
        nome: produto.nome,
        tipo: produto.tipo,
        unidade: produto.unidade,
        quantidade: novaQuantidade,
      });
      setProdutos((prev) =>
        prev.map((p) => (p.id === id ? atualizado : p))
      );
    } catch (error) {
      console.error("Erro ao atualizar quantidade:", error);
    }
  };

  const handleSetQuantidade = async (id: number, quantidade: number) => {
    const produto = produtos.find((p) => p.id === id);
    if (!produto) return;

    const novaQuantidade = Math.max(0, quantidade);
    try {
      const atualizado = await api.atualizarProduto(id, {
        nome: produto.nome,
        tipo: produto.tipo,
        unidade: produto.unidade,
        quantidade: novaQuantidade,
      });
      setProdutos((prev) =>
        prev.map((p) => (p.id === id ? atualizado : p))
      );
    } catch (error) {
      console.error("Erro ao definir quantidade:", error);
    }
  };

  const handleCadastrarProduto = async (novoProduto: { nome: string; tipo: string; unidade: string }) => {
    try {
      const criado = await api.cadastrarProduto({
        ...novoProduto,
        quantidade: 0,
      });
      setProdutos((prev) => [...prev, criado]);
    } catch (error) {
      console.error("Erro ao cadastrar produto:", error);
    }
  };

  const handleExcluirProduto = async (id: number) => {
    try {
      await api.excluirProduto(id);
      setProdutos((prev) => prev.filter((produto) => produto.id !== id));
    } catch (error) {
      console.error("Erro ao excluir produto:", error);
    }
  };

  const handleEditarProduto = async (produtoEditado: Produto) => {
    try {
      const atualizado = await api.atualizarProduto(produtoEditado.id, {
        nome: produtoEditado.nome,
        tipo: produtoEditado.tipo,
        unidade: produtoEditado.unidade,
        quantidade: produtoEditado.quantidade,
      });
      setProdutos((prev) =>
        prev.map((produto) =>
          produto.id === atualizado.id ? atualizado : produto
        )
      );
    } catch (error) {
      console.error("Erro ao editar produto:", error);
    }
  };

  return (
    <div className="min-h-screen bg-[#F3F3F3]">
      {/* Header */}
      <header className="bg-[#2C2C32] py-4 px-6 xl:py-6 xl:px-8">
        <div className="max-w-5xl xl:max-w-6xl mx-auto flex items-center justify-between">
          <SearchBar value={busca} onChange={setBusca} />
          <div className="flex items-center gap-3 xl:gap-4">
            <ActionButton onClick={() => setModalCadastroAberto(true)}>Cadastrar produto</ActionButton>
          </div>
        </div>
      </header>

      {/* Conteúdo Principal */}
      <main className="max-w-5xl xl:max-w-6xl mx-auto py-6 px-6 xl:py-8 xl:px-8">
        {loading ? (
          <div className="flex justify-center items-center py-12">
            <p className="text-gray-500">Carregando produtos...</p>
          </div>
        ) : (
          <>
            <TabelaProdutos
              produtos={produtosFiltrados}
              onUpdateQuantidade={handleUpdateQuantidade}
              onSetQuantidade={handleSetQuantidade}
              onEditarProduto={handleEditarProduto}
              onExcluirProduto={handleExcluirProduto}
            />
            
            {/* Elemento sentinela para scroll infinito */}
            <div ref={observerTarget} className="h-4" />
            
            {/* Indicador de carregando mais */}
            {loadingMore && (
              <div className="flex justify-center items-center py-6">
                <p className="text-gray-500">Carregando mais produtos...</p>
              </div>
            )}
            
            {/* Fim da lista */}
            {!hasMore && produtos.length > 0 && (
              <div className="flex justify-center items-center py-6">
                <p className="text-gray-400 text-sm">Todos os produtos foram carregados</p>
              </div>
            )}
          </>
        )}
      </main>

    
      <ModalCadastrarProduto
        isOpen={modalCadastroAberto}
        onClose={() => setModalCadastroAberto(false)}
        onCadastrar={handleCadastrarProduto}
      />
    </div>
  );
}
