// estoque-angular/src/app/features/estoque/components/modal-editar-produto/modal-editar-produto.component.ts
import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Produto } from '../../../../models/produto.model';

@Component({
  selector: 'app-modal-editar-produto',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './modal-editar-produto.component.html'
})
export class ModalEditarProdutoComponent implements OnChanges {
  @Input() isOpen: boolean = false;
  @Input() produto: Produto | null = null;

  @Output() onClose = new EventEmitter<void>();
  @Output() onEditar = new EventEmitter<Produto>();

  nome = '';
  tipo = '';
  unidade = '';

  // Substitui o truque do key={produto.id} do React
  ngOnChanges(changes: SimpleChanges) {
    if (changes['produto'] && this.produto) {
      this.nome = this.produto.nome;
      this.tipo = this.produto.tipo;
      this.unidade = this.produto.unidade;
    }
  }

  handleSubmit() {
    if (this.produto) {
      this.onEditar.emit({
        ...this.produto,
        nome: this.nome,
        tipo: this.tipo,
        unidade: this.unidade
      });
      // O onClose() do React foi substituído pelo evento abaixo
      this.onClose.emit();
    }
  }
}
<div *ngIf="isOpen && produto" class="fixed inset-0 z-50 flex items-center justify-center">
  <div class="absolute inset-0 bg-black/50" (click)="onClose.emit()"></div>

  <div class="relative bg-white rounded-lg shadow-xl w-full max-w-2xl xl:max-w-3xl mx-4">
    <div class="bg-[#2d2d2d] text-[#f5c518] font-semibold text-base xl:text-lg px-5 py-3 xl:px-6 xl:py-4 rounded-t-lg">
      Editar produto
    </div>

    <div class="p-5 xl:p-6">
      <div class="flex flex-col xl:flex-row gap-4 xl:gap-6">
        <div class="flex-1 space-y-4">
          <div>
            <label class="block text-sm xl:text-base font-medium text-gray-800 mb-1.5 xl:mb-2">
              Nome do produto
            </label>
            <input
              type="text"
              [(ngModel)]="nome"
              class="w-full bg-gray-200 rounded-md px-3 py-2 xl:px-4 xl:py-2.5 text-sm xl:text-base text-gray-800 outline-none focus:ring-2 focus:ring-[#f5c518]"
            />
          </div>

          <div>
            <label class="block text-sm xl:text-base font-medium text-gray-800 mb-1.5 xl:mb-2">
              Tipo de produto
            </label>
            <input
              type="text"
              [(ngModel)]="tipo"
              class="w-full bg-gray-200 rounded-md px-3 py-2 xl:px-4 xl:py-2.5 text-sm xl:text-base text-gray-800 outline-none focus:ring-2 focus:ring-[#f5c518]"
            />
          </div>
        </div>

        <div class="w-full xl:w-40">
          <label class="block text-sm xl:text-base font-medium text-gray-800 mb-1.5 xl:mb-2">
            Unidade
          </label>
          <div class="relative">
            <select
              [(ngModel)]="unidade"
              class="w-full bg-gray-200 rounded-md px-3 py-2 xl:px-4 xl:py-2.5 text-sm xl:text-base text-gray-800 outline-none focus:ring-2 focus:ring-[#f5c518] cursor-pointer appearance-none pr-8"
            >
              <option value="">Unidade</option>
              <option value="Kg">Kg</option>
              <option value="Un">Un</option>
              <option value="L">L</option>
              <option value="m">m</option>
            </select>
            <span class="pointer-events-none absolute inset-y-0 right-2 flex items-center">
              <svg class="w-4 h-4 text-gray-600" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" d="M19 9l-7 7-7-7" />
              </svg>
            </span>
          </div>
        </div>
      </div>

      <div class="flex justify-end gap-3 mt-6 xl:mt-8">
        <button
          (click)="onClose.emit()"
          class="px-5 py-2 xl:px-6 xl:py-2.5 text-sm xl:text-base font-medium text-gray-800 bg-white border border-gray-300 rounded-md hover:bg-gray-50 transition-colors"
        >
          Cancelar
        </button>
        <button
          (click)="handleSubmit()"
          class="px-5 py-2 xl:px-6 xl:py-2.5 text-sm xl:text-base font-medium text-black bg-[#f5c518] rounded-md hover:bg-[#e0b000] transition-colors"
        >
          Salvar
        </button>
      </div>
    </div>
  </div>
</div>

// estoque-frontend/app/components/ui/ModalEditarProduto.tsx
import { useState } from "react";
import { Produto } from "./TabelaProdutos";

interface ModalEditarProdutoProps {
  isOpen: boolean;
  produto: Produto | null;
  onClose: () => void;
  onEditar: (produto: Produto) => void;
}

export default function ModalEditarProduto({ isOpen, produto, onClose, onEditar }: ModalEditarProdutoProps) {
  if (!isOpen || !produto) return null;

  return (
    <ModalEditarProdutoContent
      key={produto.id}
      produto={produto}
      onClose={onClose}
      onEditar={onEditar}
    />
  );
}

function ModalEditarProdutoContent({
  produto,
  onClose,
  onEditar,
}: {
  produto: Produto;
  onClose: () => void;
  onEditar: (produto: Produto) => void;
}) {
  const [nome, setNome] = useState(produto.nome);
  const [tipo, setTipo] = useState(produto.tipo);
  const [unidade, setUnidade] = useState(produto.unidade);

  const handleSubmit = () => {
    onEditar({ ...produto, nome, tipo, unidade });
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Overlay */}
      <div className="absolute inset-0 bg-black/50" onClick={onClose} />

      {/* Modal */}
      <div className="relative bg-white rounded-lg shadow-xl w-full max-w-2xl xl:max-w-3xl mx-4">
        {/* Header */}
        <div className="bg-[#2d2d2d] text-[#f5c518] font-semibold text-base xl:text-lg px-5 py-3 xl:px-6 xl:py-4 rounded-t-lg">
          Editar produto
        </div>

        {/* Body */}
        <div className="p-5 xl:p-6">
          <div className="flex flex-col xl:flex-row gap-4 xl:gap-6">
            {/* Coluna esquerda */}
            <div className="flex-1 space-y-4">
              <div>
                <label className="block text-sm xl:text-base font-medium text-gray-800 mb-1.5 xl:mb-2">
                  Nome do produto
                </label>
                <input
                  type="text"
                  value={nome}
                  onChange={(e) => setNome(e.target.value)}
                  className="w-full bg-gray-200 rounded-md px-3 py-2 xl:px-4 xl:py-2.5 text-sm xl:text-base text-gray-800 outline-none focus:ring-2 focus:ring-[#f5c518]"
                />
              </div>

              <div>
                <label className="block text-sm xl:text-base font-medium text-gray-800 mb-1.5 xl:mb-2">
                  Tipo de produto
                </label>
                <input
                  type="text"
                  value={tipo}
                  onChange={(e) => setTipo(e.target.value)}
                  className="w-full bg-gray-200 rounded-md px-3 py-2 xl:px-4 xl:py-2.5 text-sm xl:text-base text-gray-800 outline-none focus:ring-2 focus:ring-[#f5c518]"
                />
              </div>
            </div>

            {/* Coluna direita */}
            <div className="w-full xl:w-40">
              <label className="block text-sm xl:text-base font-medium text-gray-800 mb-1.5 xl:mb-2">
                Unidade
              </label>
              <select
                value={unidade}
                onChange={(e) => setUnidade(e.target.value)}
                className="w-full bg-gray-200 rounded-md px-3 py-2 xl:px-4 xl:py-2.5 text-sm xl:text-base text-gray-800 outline-none focus:ring-2 focus:ring-[#f5c518] cursor-pointer"
              >
                <option value="">Unidade</option>
                <option value="Kg">Kg</option>
                <option value="Un">Un</option>
                <option value="L">L</option>
                <option value="m">m</option>
              </select>
            </div>
          </div>

          {/* Footer */}
          <div className="flex justify-end gap-3 mt-6 xl:mt-8">
            <button
              onClick={onClose}
              className="px-5 py-2 xl:px-6 xl:py-2.5 text-sm xl:text-base font-medium text-gray-800 bg-white border border-gray-300 rounded-md hover:bg-gray-50 transition-colors"
            >
              Cancelar
            </button>
            <button
              onClick={handleSubmit}
              className="px-5 py-2 xl:px-6 xl:py-2.5 text-sm xl:text-base font-medium text-black bg-[#f5c518] rounded-md hover:bg-[#e0b000] transition-colors"
            >
              Salvar
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
