// estoque-angular/src/app/features/estoque/components/modal-cadastrar-produto/modal-cadastrar-produto.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-modal-cadastrar-produto',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './modal-cadastrar-produto.component.html'
})
export class ModalCadastrarProdutoComponent {
  @Input() isOpen: boolean = false;
  
  @Output() onClose = new EventEmitter<void>();
  @Output() onCadastrar = new EventEmitter<{ nome: string; tipo: string; unidade: string }>();

  // Estados locais (Substituem os useState)
  nome = '';
  tipo = '';
  unidade = 'Un';
  
  nomeErro = '';
  tipoErro = '';
  unidadeErro = '';

  handleSubmit() {
    let hasError = false;

    // Validar nome
    if (!this.nome.trim()) {
      this.nomeErro = 'O nome do produto é obrigatório.';
      hasError = true;
    } else if (this.nome.length > 120) {
      this.nomeErro = 'O nome do produto deve ter no máximo 120 caracteres.';
      hasError = true;
    } else {
      this.nomeErro = '';
    }

    // Validar tipo
    if (!this.tipo.trim()) {
      this.tipoErro = 'O tipo do produto é obrigatório.';
      hasError = true;
    } else {
      this.tipoErro = '';
    }

    // Validar unidade
    if (!this.unidade) {
      this.unidadeErro = 'A unidade é obrigatória.';
      hasError = true;
    } else {
      this.unidadeErro = '';
    }

    if (hasError) return;

    // Emitir os dados para o componente pai
    this.onCadastrar.emit({ 
      nome: this.nome, 
      tipo: this.tipo, 
      unidade: this.unidade 
    });
    
    this.limparFormulario();
  }

  handleClose() {
    this.limparFormulario();
    this.onClose.emit();
  }

  private limparFormulario() {
    this.nome = '';
    this.tipo = '';
    this.unidade = 'Un';
    this.nomeErro = '';
    this.tipoErro = '';
    this.unidadeErro = '';
  }

  // Funções para limpar o erro ao digitar (substituem o "if (nomeErro) setNomeErro('')" do onChange no React)
  aoDigitarNome() {
    if (this.nomeErro) this.nomeErro = '';
  }

  aoDigitarTipo() {
    if (this.tipoErro) this.tipoErro = '';
  }

  aoMudarUnidade() {
    if (this.unidadeErro) this.unidadeErro = '';
  }
}
<div *ngIf="isOpen" class="fixed inset-0 z-50 flex items-center justify-center">
  <div class="absolute inset-0 bg-black/50" (click)="handleClose()"></div>

  <div class="relative bg-white rounded-lg shadow-xl w-full max-w-2xl xl:max-w-3xl mx-4">
    <div class="bg-[#2d2d2d] text-[#f5c518] font-semibold text-base xl:text-lg px-5 py-3 xl:px-6 xl:py-4 rounded-t-lg">
      Cadastro de produto
    </div>

    <div class="p-5 xl:p-6">
      <div class="flex flex-col xl:flex-row gap-4 xl:gap-6">
        <div class="flex-1 space-y-4">
          
          <div>
            <label class="block text-sm xl:text-base font-medium text-gray-800 mb-1.5 xl:mb-2">
              Nome do produto <span class="text-red-500">*</span>
            </label>
            <input
              type="text"
              [(ngModel)]="nome"
              (ngModelChange)="aoDigitarNome()"
              maxlength="120"
              [ngClass]="nomeErro ? 'focus:ring-red-500 ring-2 ring-red-500' : 'focus:ring-[#f5c518]'"
              class="w-full bg-gray-200 rounded-md px-3 py-2 xl:px-4 xl:py-2.5 text-sm xl:text-base text-gray-800 outline-none focus:ring-2"
            />
            <p *ngIf="nomeErro" class="text-red-500 text-sm mt-1">{{ nomeErro }}</p>
            <p class="text-gray-500 text-xs mt-1">{{ nome.length }}/120 caracteres</p>
          </div>

          <div>
            <label class="block text-sm xl:text-base font-medium text-gray-800 mb-1.5 xl:mb-2">
              Tipo de produto <span class="text-red-500">*</span>
            </label>
            <input
              type="text"
              [(ngModel)]="tipo"
              (ngModelChange)="aoDigitarTipo()"
              maxlength="120"
              [ngClass]="tipoErro ? 'focus:ring-red-500 ring-2 ring-red-500' : 'focus:ring-[#f5c518]'"
              class="w-full bg-gray-200 rounded-md px-3 py-2 xl:px-4 xl:py-2.5 text-sm xl:text-base text-gray-800 outline-none focus:ring-2 "
            />
            <p *ngIf="tipoErro" class="text-red-500 text-sm mt-1">{{ tipoErro }}</p>
            <p class="text-gray-500 text-xs mt-1">{{ tipo.length }}/120 caracteres</p>
          </div>
        </div>

        <div class="w-full xl:w-40">
          <label class="block text-sm xl:text-base font-medium text-gray-800 mb-1.5 xl:mb-2">
            Unidade <span class="text-red-500">*</span>
          </label>
          <div class="relative">
            <select
              [(ngModel)]="unidade"
              (ngModelChange)="aoMudarUnidade()"
              [ngClass]="unidadeErro ? 'focus:ring-red-500 ring-2 ring-red-500' : 'focus:ring-[#f5c518]'"
              class="w-full bg-gray-200 rounded-md px-3 py-2 xl:px-4 xl:py-2.5 text-sm xl:text-base text-gray-800 outline-none focus:ring-2 cursor-pointer appearance-none pr-8"
            >
              <option value="Kg">Kg</option>
              <option value="Un">Un</option>
              <option value="L">L</option>
              <option value="m">m</option>
            </select>
            <span class="pointer-events-none absolute inset-y-0 right-2 flex items-center">
              <svg class="w-4 h-4 text-gray-600" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" d="M19 9l-7 7-7-7" />
              </svg>
            </span>
          </div>
          <p *ngIf="unidadeErro" class="text-red-500 text-sm mt-1">{{ unidadeErro }}</p>
        </div>
      </div>

      <div class="flex justify-end gap-3 mt-6 xl:mt-8">
        <button
          (click)="handleClose()"
          class="px-5 py-2 xl:px-6 xl:py-2.5 text-sm xl:text-base font-medium text-gray-800 bg-white border border-gray-300 rounded-md hover:bg-gray-50 transition-colors"
        >
          Cancelar
        </button>
        <button
          (click)="handleSubmit()"
          class="px-5 py-2 xl:px-6 xl:py-2.5 text-sm xl:text-base font-medium text-black bg-[#f5c518] rounded-md hover:bg-[#e0b000] transition-colors"
        >
          Cadastrar
        </button>
      </div>
    </div>
  </div>
</div>

// estoque-frontend/app/components/ui/ModalCadastrarProduto.tsx
import { useState } from "react";

interface ModalCadastrarProdutoProps {
  isOpen: boolean;
  onClose: () => void;
  onCadastrar: (produto: { nome: string; tipo: string; unidade: string }) => void;
}

export default function ModalCadastrarProduto({ isOpen, onClose, onCadastrar }: ModalCadastrarProdutoProps) {
  const [nome, setNome] = useState("");
  const [tipo, setTipo] = useState("");
  const [unidade, setUnidade] = useState("Un");
  const [nomeErro, setNomeErro] = useState("");
  const [tipoErro, setTipoErro] = useState("");
  const [unidadeErro, setUnidadeErro] = useState("");

  if (!isOpen) return null;

  const handleSubmit = () => {
    let hasError = false;

    // Validar nome
    if (!nome.trim()) {
      setNomeErro("O nome do produto é obrigatório.");
      hasError = true;
    } else if (nome.length > 120) {
      setNomeErro("O nome do produto deve ter no máximo 120 caracteres.");
      hasError = true;
    } else {
      setNomeErro("");
    }

    // Validar tipo
    if (!tipo.trim()) {
      setTipoErro("O tipo do produto é obrigatório.");
      hasError = true;
    } else {
      setTipoErro("");
    }

    // Validar unidade
    if (!unidade) {
      setUnidadeErro("A unidade é obrigatória.");
      hasError = true;
    } else {
      setUnidadeErro("");
    }

    if (hasError) return;

    // Cadastrar produto
    onCadastrar({ nome, tipo, unidade });
    setNome("");
    setTipo("");
    setUnidade("Un");
    setNomeErro("");
    setTipoErro("");
    setUnidadeErro("");
    onClose();
  };

  const handleClose = () => {
    setNome("");
    setTipo("");
    setUnidade("Un");
    setNomeErro("");
    setTipoErro("");
    setUnidadeErro("");
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Overlay */}
      <div className="absolute inset-0 bg-black/50" onClick={handleClose} />

      {/* Modal */}
      <div className="relative bg-white rounded-lg shadow-xl w-full max-w-2xl xl:max-w-3xl mx-4">
        {/* Header */}
        <div className="bg-[#2d2d2d] text-[#f5c518] font-semibold text-base xl:text-lg px-5 py-3 xl:px-6 xl:py-4 rounded-t-lg">
          Cadastro de produto
        </div>

        {/* Body */}
        <div className="p-5 xl:p-6">
          <div className="flex flex-col xl:flex-row gap-4 xl:gap-6">
            {/* Coluna esquerda */}
            <div className="flex-1 space-y-4">
              <div>
                <label className="block text-sm xl:text-base font-medium text-gray-800 mb-1.5 xl:mb-2">
                  Nome do produto <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  value={nome}
                  onChange={(e) => {
                    setNome(e.target.value);
                    if (nomeErro) setNomeErro("");
                  }}
                  maxLength={120}
                  className={`w-full bg-gray-200 rounded-md px-3 py-2 xl:px-4 xl:py-2.5 text-sm xl:text-base text-gray-800 outline-none focus:ring-2 ${nomeErro ? 'focus:ring-red-500 ring-2 ring-red-500' : 'focus:ring-[#f5c518]'}`}
                />
                {nomeErro && (
                  <p className="text-red-500 text-sm mt-1">{nomeErro}</p>
                )}
                <p className="text-gray-500 text-xs mt-1">{nome.length}/120 caracteres</p>
              </div>

              <div>
                <label className="block text-sm xl:text-base font-medium text-gray-800 mb-1.5 xl:mb-2">
                  Tipo de produto <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  value={tipo}
                  onChange={(e) => {
                    setTipo(e.target.value);
                    if (tipoErro) setTipoErro("");
                  }}
                  maxLength={120}
                  className={`w-full bg-gray-200 rounded-md px-3 py-2 xl:px-4 xl:py-2.5 text-sm xl:text-base text-gray-800 outline-none focus:ring-2 ${tipoErro ? 'focus:ring-red-500 ring-2 ring-red-500' : 'focus:ring-[#f5c518]'}`}
                />
                {tipoErro && (
                  <p className="text-red-500 text-sm mt-1">{tipoErro}</p>
                )}
                <p className="text-gray-500 text-xs mt-1">{tipo.length}/120 caracteres</p>
              </div>
            </div>

            {/* Coluna direita */}
            <div className="w-full xl:w-40">
              <label className="block text-sm xl:text-base font-medium text-gray-800 mb-1.5 xl:mb-2">
                Unidade <span className="text-red-500">*</span>
              </label>
              <select
                value={unidade}
                onChange={(e) => {
                  setUnidade(e.target.value);
                  if (unidadeErro) setUnidadeErro("");
                }}
                className={`w-full bg-gray-200 rounded-md px-3 py-2 xl:px-4 xl:py-2.5 text-sm xl:text-base text-gray-800 outline-none focus:ring-2 cursor-pointer ${unidadeErro ? 'focus:ring-red-500 ring-2 ring-red-500' : 'focus:ring-[#f5c518]'}`}
              >
                <option value="Kg">Kg</option>
                <option value="Un">Un</option>
                <option value="L">L</option>
                <option value="m">m</option>
              </select>
              {unidadeErro && (
                <p className="text-red-500 text-sm mt-1">{unidadeErro}</p>
              )}
            </div>
          </div>

          {/* Footer */}
          <div className="flex justify-end gap-3 mt-6 xl:mt-8">
            <button
              onClick={handleClose}
              className="px-5 py-2 xl:px-6 xl:py-2.5 text-sm xl:text-base font-medium text-gray-800 bg-white border border-gray-300 rounded-md hover:bg-gray-50 transition-colors"
            >
              Cancelar
            </button>
            <button
              onClick={handleSubmit}
              className="px-5 py-2 xl:px-6 xl:py-2.5 text-sm xl:text-base font-medium text-black bg-[#f5c518] rounded-md hover:bg-[#e0b000] transition-colors"
            >
              Cadastrar
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
