// estoque-angular/src/app/features/estoque/components/quantidade-controle/quantidade-controle.component.ts
import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-quantidade-controle',
  standalone: true,
  templateUrl: './quantidade-controle.component.html'
})
export class QuantidadeControleComponent implements OnChanges, OnDestroy {
  @Input() quantidade: number = 0;
  
  @Output() onIncrement = new EventEmitter<void>();
  @Output() onDecrement = new EventEmitter<void>();
  @Output() onChange = new EventEmitter<number>();

  valorLocal: number = 0;
  private timeoutId: any;

  // Equivalente ao: useEffect(() => setValorLocal(quantidade), [quantidade])
  ngOnChanges(changes: SimpleChanges) {
    if (changes['quantidade']) {
      this.valorLocal = this.quantidade;
    }
  }

  // Limpeza de memória (clearTimeout do useEffect)
  ngOnDestroy() {
    if (this.timeoutId) {
      clearTimeout(this.timeoutId);
    }
  }

  handleChange(event: Event) {
    const inputElement = event.target as HTMLInputElement;
    const valor = parseInt(inputElement.value, 10);

    if (!isNaN(valor) && valor >= 0) {
      this.valorLocal = valor;
      this.agendarAtualizacao();
    } else {
      // Se apagar tudo ou puser valor inválido, volta visualmente ao valor anterior
      inputElement.value = this.valorLocal.toString();
    }
  }

  // Equivalente ao: useEffect com setTimeout de 500ms
  private agendarAtualizacao() {
    if (this.valorLocal === this.quantidade) return;

    if (this.timeoutId) {
      clearTimeout(this.timeoutId);
    }

    this.timeoutId = setTimeout(() => {
      this.onChange.emit(this.valorLocal);
    }, 500);
  }
}
<div class="flex items-center gap-0.5 xl:gap-1">
  <button
    (click)="onIncrement.emit()"
    class="flex items-center justify-center w-5 h-5 xl:w-6 xl:h-6 rounded-full bg-[#f5c518] hover:bg-[#e0b000] text-black font-bold text-xs xl:text-sm transition-colors"
  >
    +
  </button>
  
  <input
    type="number"
    min="0"
    [value]="valorLocal"
    (input)="handleChange($event)"
    class="w-10 h-5 xl:w-12 xl:h-6 text-center text-xs xl:text-sm text-black border border-gray-300 rounded bg-white outline-none focus:ring-1 focus:ring-[#f5c518] [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
  />
  
  <button
    (click)="onDecrement.emit()"
    class="flex items-center justify-center w-5 h-5 xl:w-6 xl:h-6 rounded-full bg-[#f5c518] hover:bg-[#e0b000] text-black font-bold text-xs xl:text-sm transition-colors"
  >
    −
  </button>
</div>

// estoque-frontend/app/components/ui/QuantidadeControle.tsx
interface QuantidadeControleProps {
  quantidade: number;
  onIncrement: () => void;
  onDecrement: () => void;
  onChange?: (valor: number) => void;
}

export default function QuantidadeControle({ quantidade, onIncrement, onDecrement, onChange }: QuantidadeControleProps) {
  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const valor = parseInt(e.target.value, 10);
    if (!isNaN(valor) && valor >= 0 && onChange) {
      onChange(valor);
    }
  };

  return (
    <div className="flex items-center gap-0.5 xl:gap-1 ">
      <button
        onClick={onIncrement}
        className="flex items-center justify-center w-5 h-5 xl:w-6 xl:h-6 rounded-full bg-[#f5c518] hover:bg-[#e0b000] text-black font-bold text-xs xl:text-sm transition-colors"
      >
        +
      </button>
      <input
        type="number"
        min="0"
        value={quantidade}
        onChange={handleChange}
        className="w-10 h-5 xl:w-12 xl:h-6 text-center text-xs xl:text-sm border border-gray-300 rounded bg-white outline-none focus:ring-1 focus:ring-[#f5c518] [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
      />
      <button
        onClick={onDecrement}
        className="flex items-center justify-center w-5 h-5 xl:w-6 xl:h-6 rounded-full bg-[#f5c518] hover:bg-[#e0b000] text-black font-bold text-xs xl:text-sm transition-colors"
      >
        −
      </button>
    </div>
  );
}
